---
- name: Ensure Nginx is installed
  ansible.builtin.yum:
    name: nginx
    state: present

- name: Ensure latest version of Nginx is installed
  ansible.builtin.yum:
    name: nginx
    state: latest

- name: Ensure Nginx service is started
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Deploy Nginx configuration
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: Restart Nginx

- name: Deploy index.html to Nginx
  ansible.builtin.copy:
    src: index.html
    dest: /usr/share/nginx/html/index.html

- name: Ensure HTTP port is open in the firewall
  ansible.builtin.firewalld:
    service: http
    permanent: true
    state: enabled

- name: Ensure HTTPS port is open in the firewall
  ansible.builtin.firewalld:
    service: https
    permanent: true
    state: enabled

- name: Ensure SELinux allows Nginx traffic
  ansible.builtin.command: setsebool -P httpd_can_network_connect 1

- name: Ensure Nginx logs directory exists
  ansible.builtin.file:
    path: /var/log/nginx
    state: directory
    owner: nginx
    group: nginx

- name: Remove default Nginx HTML files
  ansible.builtin.file:
    path: /usr/share/nginx/html/index.nginx-debian.html
    state: absent

- name: Backup existing Nginx configuration
  ansible.builtin.copy:
    src: /etc/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf.bak
    remote_src: yes

- name: Create SSL directory
  ansible.builtin.file:
    path: /etc/nginx/ssl
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Deploy SSL configuration
  ansible.builtin.template:
    src: nginx_ssl.conf.j2
    dest: /etc/nginx/conf.d/ssl.conf
  notify: Restart Nginx

- name: Clear Nginx cache
  ansible.builtin.command: nginx -s reload

- name: Test Nginx configuration
  ansible.builtin.command: nginx -t
  register: nginx_test
  ignore_errors: true

- name: Ensure Nginx configuration is valid
  ansible.builtin.fail:
    msg: "Nginx configuration test failed"
  when: nginx_test.rc != 0
